### ISSUE TITLE
4.8.2 to 4.8.4 signature failure

### ISSUE THREAD

**Issue by luozewei** [ITfoxtec/ITfoxtec.Identity.Saml2#133] opened 2023-03-23 03:43 UTC
I upgraded from version 4.8.2 to 4.8.4 without making any modifications to the code. However, when trying to access OKTA, I encountered a signature failure. I am unsure what needs to be adjusted in order to fix this issue. When I revert back to the previous version, everything works normally. Nevertheless, I desire to utilize the most recent features and functionalities. How should I address this issue?
"Issuer": "xxxx",
"SignatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
"CertificateValidationMode": "None",
"RevocationMode": "NoCheck"

**Comment by luozewei** [comment] 2023-03-23 03:44
2023-03-23 03:32:30.209 +00:00 [INF] SignatureAlgorithm:http://www.w3.org/2001/04/xmldsig-more#rsa-sha256,CertificateValidationMode:None,RevocationMode:NoCheck,Issuer:Yeeflow
2023-03-23 03:32:30.297 +00:00 [INF] SAMLResponse:PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbDJwOlJlc3BvbnNlIERlc3RpbmF0aW9uPSJodHRwczovL3VhdGxvZ2luLnllZWZsb3cuY24vc2FtbDIvYXNzZXJ0aW9uL29rdGEiIElEPSJpZDE4MzMxOTk3NTQ4ODE4MTY2OTE1ODMwMDYwIiBJblJlc3BvbnNlVG89Il82ZTdmZTc1Yi1iNmQ3LTQzZWItYjdkMC0zZTgzZmIyNjFmMGIiIElzc3VlSW5zdGFudD0iMjAyMy0wMy0yM1QwMzozMjoyOS4zMDdaIiBWZXJzaW9uPSIyLjAiIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiPjxzYW1sMjpJc3N1ZXIgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDplbnRpdHkiIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj5odHRwOi8vd3d3Lm9rdGEuY29tL2V4azhseWk4MGs1cEJ3NUh3NWQ3PC9zYW1sMjpJc3N1ZXI+PGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PGRzOlNpZ25lZEluZm8+PGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxkc2lnLW1vcmUjcnNhLXNoYTI1NiIvPjxkczpSZWZlcmVuY2UgVVJJPSIjaWQxODMzMTk5NzU0ODgxODE2NjkxNTgzMDA2MCI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIi8+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI+PGVjOkluY2x1c2l2ZU5hbWVzcGFjZXMgUHJlZml4TGlzdD0ieHMiIHhtbG5zOmVjPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48L2RzOlRyYW5zZm9ybT48L2RzOlRyYW5zZm9ybXM+PGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZW5jI3NoYTI1NiIvPjxkczpEaWdlc3RWYWx1ZT56UlZSeTVvVkpSdFg1RVRneDI3UzZrQW1qNEN3WTJERGFYaGx0UFdTSnZNPTwvZHM6RGlnZXN0VmFsdWU+PC9kczpSZWZlcmVuY2U+PC9kczpTaWduZWRJbmZvPjxkczpTaWduYXR1cmVWYWx1ZT5keENZQlVqMUlrMy9qR3BHV2hRMDd6Zy9YczZ5OXZDVEZzMmtiYlIxUEwvOXF0amdkTVFsOE5VZ01idUo1ZHFuZk1PY3R0V0VLUXo0VEl5UWkrZ09xOWF6Z2pPWThRczV4YkVsT3p1NVVFbUpkeWsvZG92V3NoWjFOMnRGWFlzMDJGOE50anJkRmJadUMvQ2NDbFF3MlEvZk5aNnRLNnVDRVAwcEU0Q3U3dzNlenVnblpzem1GVjZpZ2ZXczZ6UjdGRTcwUUsxQ0F1Q2VRbCttM1dQd0t1TjI4RlJqSlZ2bSsyUnZqY2llWFRTaERUOUx0aU9tSVRNVm9ITFN5Wm44N1JENy9HT1l5QmxXam1aMVpTUFpseDBVQlRMa1FqRlVjRUxXT0Y5S01XRXdkYTlqUnJKdVppRGhxK1FGOVE4ZkJvTVFPZXYvaklCQkNNWjFTZjZSYUE9PTwvZHM6U2lnbmF0dXJlVmFsdWU+PGRzOktleUluZm8+PGRzOlg1MDlEYXRhPjxkczpYNTA5Q2VydGlmaWNhdGU+TUlJRHFEQ0NBcENnQXdJQkFnSUdBWWE2a2JOcE1BMEdDU3FHU0liM0RRRUJDd1VBTUlHVU1Rc3dDUVlEVlFRR0V3SlZVekVUTUJFRwpBMVVFQ0F3S1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeVlXNWphWE5qYnpFTk1Bc0dBMVVFQ2d3RVQydDBZVEVVCk1CSUdBMVVFQ3d3TFUxTlBVSEp2ZG1sa1pYSXhGVEFUQmdOVkJBTU1ER1JsZGkwd05ETTFNakkwTnpFY01Cb0dDU3FHU0liM0RRRUoKQVJZTmFXNW1iMEJ2YTNSaExtTnZiVEFlRncweU16QXpNRGN3TlRNME5UWmFGdzB6TXpBek1EY3dOVE0xTlRaYU1JR1VNUXN3Q1FZRApWUVFHRXdKVlV6RVRNQkVHQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RU5NQXNHCkExVUVDZ3dFVDJ0MFlURVVNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RlRBVEJnTlZCQU1NREdSbGRpMHdORE0xTWpJME56RWMKTUJvR0NTcUdTSWIzRFFFSkFSWU5hVzVtYjBCdmEzUmhMbU52YlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQU9JYU9UcVFtTEtYNERzZGE1TjVnQ2dKcnM3WlluUnRvM2UvRnBGaHFrclFVZkNMNC82YStEWmhHVzJ1S0FST1RVZWtxMG5kCndXMFEvYTByYzkvaTIrbjM1OGk2TC8rWVFYY3BmN1RPTWpIWDZRbWNQUEJiVnF4YVZhZEJSNm5lQkgvcGw5dkV1dGZBbEF2RWtvblAKNXJLZ2hhU3RoL0xYUzcxMHU0bW5YMUVBOE9sa20xOFlYWjVRMXQ2UTJ0ODh0V3BXZ2dVc0FOOEd1dnlwLzBHTG9IWE9SK2s0d1p0cQpmR0hIeURyK1UwNStVYTAyY3ZyNVpxUEVqR0FxdkFJU2ZNQzk1MStqSzRlVndKL2xTQWdQWW5lekZpdnRkMGQvSmZlSUVPYllBWEI4CkRwaUFGWlVGaE0xN2x1c2pIS3pZZ0c5V0U2YlJpVFpVaS9LN3J0SGJBUXNDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKYURPcVYvYTJvM08ySlNWSHhuUlZlcFp5R2dRSkFoZ2dUem1YNHV0TDJUOHF4WjhuYUx6ZTFJSGNrTGI4aGRaN0NtR3BxQVBGRmhZLwp4RCt5aFlKYUdUNW4xZ0JtRzlLMml0NFZxTjFDYk90Vzk3S1kwcDRBV3lVQSt0UXVXRFhlcTFKRUFKbHhJaGlCbEx0M2oyamsvNVBuClhnUW0rMUFVb1A5RnFCK0laYUYxME1BTjQweVJzditSWkxjb0N5dVJLRmZxZCt2dFp6bW1WamFVV2VaaXpWamV6SmxuUmJreGg4b1cKMUhyQ3UzT082dFg3YVk2Umd4VnZsRmxiaUNtVnUxd3EwOFVUME15TXo4RnBhanA0S3lYZlBETzZnUTBYcXJja09Ma2JBOWRlb0RsNQpxSStnTXlsSy8zRDZwWGJxNDRQcGhFcWFQYmRiTzV0QU1PaHM1UT09PC9kczpYNTA5Q2VydGlmaWNhdGU+PC9kczpYNTA5RGF0YT48L2RzOktleUluZm8+PC9kczpTaWduYXR1cmU+PHNhbWwycDpTdGF0dXMgeG1sbnM6c2FtbDJwPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiPjxzYW1sMnA6U3RhdHVzQ29kZSBWYWx1ZT0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnN0YXR1czpTdWNjZXNzIi8+PC9zYW1sMnA6U3RhdHVzPjxzYW1sMjpBc3NlcnRpb24gSUQ9ImlkMTgzMzE5OTc1NDg5NzExNzkxMDkwMjc2NjcwIiBJc3N1ZUluc3RhbnQ9IjIwMjMtMDMtMjNUMDM6MzI6MjkuMzA3WiIgVmVyc2lvbj0iMi4wIiB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIj48c2FtbDI6SXNzdWVyIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5IiB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+aHR0cDovL3d3dy5va3RhLmNvbS9leGs4bHlpODBrNXBCdzVIdzVkNzwvc2FtbDI6SXNzdWVyPjxkczpTaWduYXR1cmUgeG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPjxkczpTaWduZWRJbmZvPjxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8+PGRzOlNpZ25hdHVyZU1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZHNpZy1tb3JlI3JzYS1zaGEyNTYiLz48ZHM6UmVmZXJlbmNlIFVSST0iI2lkMTgzMzE5OTc1NDg5NzExNzkxMDkwMjc2NjcwIj48ZHM6VHJhbnNmb3Jtcz48ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiLz48ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIj48ZWM6SW5jbHVzaXZlTmFtZXNwYWNlcyBQcmVmaXhMaXN0PSJ4cyIgeG1sbnM6ZWM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvZHM6VHJhbnNmb3JtPjwvZHM6VHJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2Ii8+PGRzOkRpZ2VzdFZhbHVlPjR6em9SU05pdzJseHpQM0VUdzc4Z05pUTlkWFNIalhwQmQ4V3hSc3JSK1k9PC9kczpEaWdlc3RWYWx1ZT48L2RzOlJlZmVyZW5jZT48L2RzOlNpZ25lZEluZm8+PGRzOlNpZ25hdHVyZVZhbHVlPkpESFFETlhUQmV1cUp3amU1RXJLVEM3M1dJbUp6OVFxYVZ3RENVQ09rUW52Z2kzSnZHNDJCRDRPTFdFOG1iazFUak9PenhLdEdOMGNYRFNnTjhtWUwxZkJuVU1YdmdJaGZOWW5XazlmaXY0VHV4TjFNQVRWQ2xFM2NjRFkrRndNNWorVUdqczZPSVVDQ005Y0JVYmJ0UXFaYnAyN1lVTWJkN3JCOUw3UnRVQ2xyTkVFVE5NWDZIeG82Z0lPT2NCek14bkk0eDRrWnowMURVYUEvRmVLVkJzcmwwcnlwejFUTHpsOENpc2hyYzg1eVM0NW1qdjRqRytVQlZEbUx0alpmQVdCc2Vaa3Mwa1AvbE83cHRrQ2l4K0tkejgzNWNNaWR5M3ZRcXFZemRoNGJTVXc3eDlNMDRNaldXSm0wZCs4WjlGaDNmZThNUVlrTGMwam1Xc3BpZz09PC9kczpTaWduYXR1cmVWYWx1ZT48ZHM6S2V5SW5mbz48ZHM6WDUwOURhdGE+PGRzOlg1MDlDZXJ0aWZpY2F0ZT5NSUlEcURDQ0FwQ2dBd0lCQWdJR0FZYTZrYk5wTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdVTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHCkExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1amFYTmpiekVOTUFzR0ExVUVDZ3dFVDJ0MFlURVUKTUJJR0ExVUVDd3dMVTFOUFVISnZkbWxrWlhJeEZUQVRCZ05WQkFNTURHUmxkaTB3TkRNMU1qSTBOekVjTUJvR0NTcUdTSWIzRFFFSgpBUllOYVc1bWIwQnZhM1JoTG1OdmJUQWVGdzB5TXpBek1EY3dOVE0wTlRaYUZ3MHpNekF6TURjd05UTTFOVFphTUlHVU1Rc3dDUVlEClZRUUdFd0pWVXpFVE1CRUdBMVVFQ0F3S1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeVlXNWphWE5qYnpFTk1Bc0cKQTFVRUNnd0VUMnQwWVRFVU1CSUdBMVVFQ3d3TFUxTlBVSEp2ZG1sa1pYSXhGVEFUQmdOVkJBTU1ER1JsZGkwd05ETTFNakkwTnpFYwpNQm9HQ1NxR1NJYjNEUUVKQVJZTmFXNW1iMEJ2YTNSaExtTnZiVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBT0lhT1RxUW1MS1g0RHNkYTVONWdDZ0pyczdaWW5SdG8zZS9GcEZocWtyUVVmQ0w0LzZhK0RaaEdXMnVLQVJPVFVla3EwbmQKd1cwUS9hMHJjOS9pMituMzU4aTZMLytZUVhjcGY3VE9NakhYNlFtY1BQQmJWcXhhVmFkQlI2bmVCSC9wbDl2RXV0ZkFsQXZFa29uUAo1cktnaGFTdGgvTFhTNzEwdTRtblgxRUE4T2xrbTE4WVhaNVExdDZRMnQ4OHRXcFdnZ1VzQU44R3V2eXAvMEdMb0hYT1IrazR3WnRxCmZHSEh5RHIrVTA1K1VhMDJjdnI1WnFQRWpHQXF2QUlTZk1DOTUxK2pLNGVWd0ovbFNBZ1BZbmV6Rml2dGQwZC9KZmVJRU9iWUFYQjgKRHBpQUZaVUZoTTE3bHVzakhLellnRzlXRTZiUmlUWlVpL0s3cnRIYkFRc0NBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQphRE9xVi9hMm8zTzJKU1ZIeG5SVmVwWnlHZ1FKQWhnZ1R6bVg0dXRMMlQ4cXhaOG5hTHplMUlIY2tMYjhoZFo3Q21HcHFBUEZGaFkvCnhEK3loWUphR1Q1bjFnQm1HOUsyaXQ0VnFOMUNiT3RXOTdLWTBwNEFXeVVBK3RRdVdEWGVxMUpFQUpseEloaUJsTHQzajJqay81UG4KWGdRbSsxQVVvUDlGcUIrSVphRjEwTUFONDB5UnN2K1JaTGNvQ3l1UktGZnFkK3Z0WnptbVZqYVVXZVppelZqZXpKbG5SYmt4aDhvVwoxSHJDdTNPTzZ0WDdhWTZSZ3hWdmxGbGJpQ21WdTF3cTA4VVQwTXlNejhGcGFqcDRLeVhmUERPNmdRMFhxcmNrT0xrYkE5ZGVvRGw1CnFJK2dNeWxLLzNENnBYYnE0NFBwaEVxYVBiZGJPNXRBTU9oczVRPT08L2RzOlg1MDlDZXJ0aWZpY2F0ZT48L2RzOlg1MDlEYXRhPjwvZHM6S2V5SW5mbz48L2RzOlNpZ25hdHVyZT48c2FtbDI6U3ViamVjdCB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+PHNhbWwyOk5hbWVJRCBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjEuMTpuYW1laWQtZm9ybWF0OmVtYWlsQWRkcmVzcyI+bWlrZUBrLXNvbHZlZ2xvYmFsLmNvbTwvc2FtbDI6TmFtZUlEPjxzYW1sMjpTdWJqZWN0Q29uZmlybWF0aW9uIE1ldGhvZD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmNtOmJlYXJlciI+PHNhbWwyOlN1YmplY3RDb25maXJtYXRpb25EYXRhIEluUmVzcG9uc2VUbz0iXzZlN2ZlNzViLWI2ZDctNDNlYi1iN2QwLTNlODNmYjI2MWYwYiIgTm90T25PckFmdGVyPSIyMDIzLTAzLTIzVDAzOjM3OjI5LjMwOFoiIFJlY2lwaWVudD0iaHR0cHM6Ly91YXRsb2dpbi55ZWVmbG93LmNuL3NhbWwyL2Fzc2VydGlvbi9va3RhIi8+PC9zYW1sMjpTdWJqZWN0Q29uZmlybWF0aW9uPjwvc2FtbDI6U3ViamVjdD48c2FtbDI6Q29uZGl0aW9ucyBOb3RCZWZvcmU9IjIwMjMtMDMtMjNUMDM6Mjc6MjkuMzA4WiIgTm90T25PckFmdGVyPSIyMDIzLTAzLTIzVDAzOjM3OjI5LjMwOFoiIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj48c2FtbDI6QXVkaWVuY2VSZXN0cmljdGlvbj48c2FtbDI6QXVkaWVuY2U+WWVlZmxvdzwvc2FtbDI6QXVkaWVuY2U+PC9zYW1sMjpBdWRpZW5jZVJlc3RyaWN0aW9uPjwvc2FtbDI6Q29uZGl0aW9ucz48c2FtbDI6QXV0aG5TdGF0ZW1lbnQgQXV0aG5JbnN0YW50PSIyMDIzLTAzLTIzVDAzOjMyOjI5LjMwN1oiIFNlc3Npb25JbmRleD0iXzZlN2ZlNzViLWI2ZDctNDNlYi1iN2QwLTNlODNmYjI2MWYwYiIgeG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPjxzYW1sMjpBdXRobkNvbnRleHQ+PHNhbWwyOkF1dGhuQ29udGV4dENsYXNzUmVmPnVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0PC9zYW1sMjpBdXRobkNvbnRleHRDbGFzc1JlZj48L3NhbWwyOkF1dGhuQ29udGV4dD48L3NhbWwyOkF1dGhuU3RhdGVtZW50PjxzYW1sMjpBdHRyaWJ1dGVTdGF0ZW1lbnQgeG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPjxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0ibmFtZSIgTmFtZUZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmF0dHJuYW1lLWZvcm1hdDpiYXNpYyI+PHNhbWwyOkF0dHJpYnV0ZVZhbHVlIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9InhzOnN0cmluZyI+TWlrZSBrPC9zYW1sMjpBdHRyaWJ1dGVWYWx1ZT48L3NhbWwyOkF0dHJpYnV0ZT48c2FtbDI6QXR0cmlidXRlIE5hbWU9ImVhbWlsIiBOYW1lRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXR0cm5hbWUtZm9ybWF0OmJhc2ljIj48c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj5taWtlQGstc29sdmVnbG9iYWwuY29tPC9zYW1sMjpBdHRyaWJ1dGVWYWx1ZT48L3NhbWwyOkF0dHJpYnV0ZT48L3NhbWwyOkF0dHJpYnV0ZVN0YXRlbWVudD48L3NhbWwyOkFzc2VydGlvbj48L3NhbWwycDpSZXNwb25zZT4=

**Comment by Revsgaard** [comment] 2023-03-24 21:37
That doesn't sound good.
In what flow are you experiencing the signature failure? 

- Is it the Authn response you receive from OKTA that fails? 
- Is the Authn response signed on message or assertion level or both? 
- Are you using the POST binding?

Would it somehow be possible for me to test it with OKTA?

**Comment by luozewei** [comment] 2023-03-29 02:54
`           Saml2Configuration config = GetMetadata(domain); 
            var binding = new Saml2PostBinding();
            var saml2AuthnResponse = new Saml2AuthnResponse(config);
            var httpRequest = Request.ToGenericHttpRequest(); 
            _logger.LogInformation("SAMLResponse:" + Request.Form["SAMLResponse"]);
            _logger.LogInformation("RelayState:" + Request.Form["RelayState"]);  
            binding.ReadSamlResponse(httpRequest, saml2AuthnResponse); 
            if (saml2AuthnResponse.Status != Saml2StatusCodes.Success)
            {
                throw new AuthenticationException($"SAML Response status: {saml2AuthnResponse.Status}");
            }`
The failure occurred due to receipt of an OTKA message indicating a signature error. The aforementioned represents the manner in which I received the message via POST.

**Comment by luozewei** [comment] 2023-03-29 02:54
`           Saml2Configuration config = GetMetadata(domain); 
            var binding = new Saml2PostBinding();
            var saml2AuthnResponse = new Saml2AuthnResponse(config);
            var httpRequest = Request.ToGenericHttpRequest(); 
            _logger.LogInformation("SAMLResponse:" + Request.Form["SAMLResponse"]);
            _logger.LogInformation("RelayState:" + Request.Form["RelayState"]);  
            binding.ReadSamlResponse(httpRequest, saml2AuthnResponse); 
            if (saml2AuthnResponse.Status != Saml2StatusCodes.Success)
            {
                throw new AuthenticationException($"SAML Response status: {saml2AuthnResponse.Status}");
            }`
The failure occurred due to receipt of an OTKA message indicating a signature error. The aforementioned represents the manner in which I received the message via POST.

**Comment by luozewei** [comment] 2023-03-29 02:55
I referenced this code and found the configuration and code to be nearly identical.: https://developer.okta.com/blog/2020/10/23/how-to-authenticate-with-saml-in-aspnet-core-and-csharp

**Comment by zima702** [comment] 2023-03-29 20:18
I referenced the same Okta implementation, and I am also experiencing the same “Invalid Signature” issue as well, with versions 4.8.4 and 4.8.5. It seems to occur on the unbind in the AssertionConsumerService for me. I didn’t see any SO posts with the same issue, so I reverted back to 4.8.2.

**Comment by Revsgaard** [comment] 2023-03-31 11:18
I have just configured an application in Okta and testet the new [version 4.8.5](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.5), it works perfectly.

I have tested with the [TestWebAppCore sample](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/tree/master/test/TestWebAppCore) configured with an Okta metadata `https://trial-9793968.okta.com/app/exk4siv8qyImU50Im697/sso/saml/metadata`.

**Comment by luozewei** [comment] 2023-04-03 03:16
I tried it, and the new 4.8.5 will work, too. My Demo code.
`
  [AllowAnonymous]
    [Route("saml2")]
    public class Saml2Controller : Controller
    {
        IHttpClientFactory httpClientFactory; 
        const string relayStateReturnUrl = "ReturnUrl";
        private readonly Saml2Configuration config;
        string metadata = "https://dev-04352247.okta.com/app/exk8ym64q74ERhP675d7/sso/saml/metadata";
        public Saml2Controller(IHttpClientFactory _httpClientFactory)
        {
            httpClientFactory = _httpClientFactory;
            config = GetMetadata();
        }

      
        private Saml2Configuration GetMetadata()
        {

            var config = new Saml2Configuration()
            {
                Issuer = "TestWebApp3.1",
                SignatureAlgorithm = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                CertificateValidationMode = X509CertificateValidationMode.None,
                RevocationMode = X509RevocationMode.NoCheck
            };
            config.AllowedAudienceUris.Add(config.Issuer);
            var entityDescriptor = new EntityDescriptor();
            entityDescriptor.ReadIdPSsoDescriptorFromUrlAsync(httpClientFactory, new Uri(metadata)).GetAwaiter().GetResult();
            if (entityDescriptor.IdPSsoDescriptor != null)
            {
                config.Issuer = entityDescriptor.EntityId;
                config.SingleSignOnDestination = entityDescriptor.IdPSsoDescriptor.SingleSignOnServices.First().Location;
                config.SingleLogoutDestination = entityDescriptor.IdPSsoDescriptor?.SingleLogoutServices?.First()?.Location;
                config.SignatureValidationCertificates.AddRange(entityDescriptor.IdPSsoDescriptor.SigningCertificates);
                if (config.SignatureValidationCertificates.Count <= 0)
                {
                    throw new Exception("The IdP signing certificates has expired.");
                }
                if (entityDescriptor.IdPSsoDescriptor.WantAuthnRequestsSigned.HasValue)
                {
                    config.SignAuthnRequest = entityDescriptor.IdPSsoDescriptor.WantAuthnRequestsSigned.Value;
                }
            }
            else
            {
                throw new Exception("IdPSsoDescriptor not loaded from metadata.");
            }
            return config;
        }
        [Route("Login")]
        public IActionResult Login(string returnUrl = null)
        {
            var binding = new Saml2RedirectBinding();
            binding.SetRelayStateQuery(new Dictionary<string, string> { { relayStateReturnUrl, returnUrl ?? Url.Content("~/") } });

            return binding.Bind(new Saml2AuthnRequest(config)
            {

            }).ToActionResult();
        }
        [Route("AssertionConsumerService")]
        public async Task<IActionResult> AssertionConsumerServiceAsync()
        {
            var binding = new Saml2PostBinding();
            var saml2AuthnResponse = new Saml2AuthnResponse(config);

            binding.ReadSamlResponse(Request.ToGenericHttpRequest(), saml2AuthnResponse);
            if (saml2AuthnResponse.Status != Saml2StatusCodes.Success)
            {
                throw new AuthenticationException($"SAML Response status: {saml2AuthnResponse.Status}");
            }
            binding.Unbind(Request.ToGenericHttpRequest(), saml2AuthnResponse);
            await saml2AuthnResponse.CreateSession(HttpContext);
            var relayStateQuery = binding.GetRelayStateQuery();
            var returnUrl = relayStateQuery.ContainsKey(relayStateReturnUrl) ? relayStateQuery[relayStateReturnUrl] : Url.Content("~/");
            return Redirect(returnUrl);
        }

    }
`

**Comment by luozewei** [comment] 2023-04-03 03:20
Because I have multiple merchants on my side, and there are too many differences in the configuration of each merchant, I always initialize the config when there is a request to enter. I don't know if there is any impact.

**Comment by Revsgaard** [comment] 2023-04-03 08:57
To clarify. [luozewei](https://github.com/luozewei) are you saying that the 4.8.5 version is working for you? Without any signature errors?

**Comment by Revsgaard** [comment] 2023-04-08 09:58
Thank you for your help with this error. The problem is resolved in version [4.8.5](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.5)

**Closed by Revsgaard** 2023-04-08 09:58 UTC
