### ISSUE TITLE
Error thrown when ArtifactResponse StatusCode is Success but Inner StatusCode is Responder

### ISSUE THREAD

**Issue by JoanGil** [ITfoxtec/ITfoxtec.Identity.Saml2#160] opened 2023-11-10 11:21 UTC
Hello!

We are facing an issue while reading the `ArtifactResponse` from a canceled request from `DigiD`:
![image](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/assets/4748759/9a005f1d-ce21-4af1-a854-78ddab4929f9)

When canceling the login, `DigiD` sends us an `ArtifactResponse` with a `Success` 'general' StatusCode but also with an inner `Responder` StatusCode (which is saying that the login request is canceled). We have been debugging the library and it seems that an exception is thrown because the XML doesn't contain an `Assertion` tag: `There is not exactly one Assertion element in the inner Artifact element.` Here you can see the path we have followed to identify the possible issue:

![image](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/assets/4748759/b6fd76a6-4e26-4696-a306-23fc88c30414)

![image](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/assets/4748759/c89237dc-3a51-4b10-91c6-f8883190e992)

![image](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/assets/4748759/38973121-40aa-46f8-9efb-dd8429f43bcb)

![image](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/assets/4748759/e3be1056-fd1c-4fee-aef9-601f9347ca90)

When comparing two `ArtifactResponse`s from a Successful login vs a Canceled login, we can see that the successful one contains an `Assertion` element and the canceled one doesn't.
![image](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/assets/4748759/008205a7-25fd-4325-b245-0082e5316b91)

This is the raw XML that we receive:
[artifact response canceled.txt](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/files/13318688/artifact.response.canceled.txt)

Our question would be: Is there a way to identify when the response is 'canceled' so we can send the user to a proper redirection page, instead of throwing an exception? 

If you need more information, please let me know. And thanks for your time!

Used version for the tests: [`4.10.4`](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.10.4)

**Comment by Revsgaard** [comment] 2023-11-10 12:27
I'll look into the problem.

Would you like to sponsor this library? It would be much appreciated.

**Comment by JoanGil** [comment] 2023-11-10 12:40
Thanks @Revsgaard!

I appreciate the offer. I'll need to discuss potential sponsorship with my company and will get back to you.

**Comment by Revsgaard** [comment] 2023-11-13 21:34
I think the problem is resolved in commit https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/0c3547969d0a8b749ee2f0b6c8cf92f9780fefe9, please take a look.

**Comment by JoanGil** [comment] 2023-11-14 10:51
Your commit (https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/0c3547969d0a8b749ee2f0b6c8cf92f9780fefe9) solved the issue! Thanks for the effort! 🙏

**Comment by Revsgaard** [comment] 2023-11-14 11:11
I'll release a new version after .NET 8 has been released. If you find more problems, they can probably be included.

**Comment by JoanGil** [comment] 2023-11-14 12:40
Perfect, thanks! If we find anything else, we will let you know.

**Comment by Revsgaard** [comment] 2023-11-15 13:20
Expect it to be released within 1 or 2 weeks.

**Closed by Revsgaard** 2023-11-15 13:20 UTC
